const Strings = {
    live: 'LIVE',
    connections: 'CONNECTIONS',

    // Login
    user_name: 'Username',
    password: 'Password',
    login: 'Log in',
    create: 'Create',
    forgot_password: 'Forgot password',
    no_account_msg: `Don't have an Account?`,
    register: 'Register',
    mobile_number:'Mobile Number',
    mpin:'4 Digit MPIN',
    // Register
    confirm_password: 'Confirm Pwd',
    first_name: 'First Name',
    last_name: 'Last Name',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    others: 'Others',
    dob: 'DOB',
    email: 'Email',
    phone_no: 'Phone No',
    company: 'Company',
    ctc: 'CTC',
    skill: 'Skill',
    industry: 'Industry',
    functional_area: 'Functional Area',
    functional_role: 'Functional Role',
    notice_period: 'Notice Period',
    exp: 'Exp',
    current_location: 'Current Location',
    preferred_location: 'Preferred Location',
    languages_known: 'Languages Known',
    upload_resume: 'Upload Resume',
    disability_person: 'Person with disability',
    submit: 'Submit',
    password_error_msg: `Required atleast 1 Uppercase, 1 Lowercase & 1 special char with min 8 chars`,
    confirm_pwd_mismatch_error: 'Invalid confirm password! Try Again!',
    email_error: 'Please enter valid email!',
    phone_no_error: 'Please enter your 10 digit phone number!',

    home: 'Home',
    dashboard:'Dashboard',
    sales: 'Sales',
    report: 'Reports',
    expenses: 'Expenses',
    customer: 'Customer',
    alerts: 'Alerts',

};

export default Strings;